"""DML pricer training orchestration.

Two-stage:
    (1) Pretrain on closed-form Black-Scholes synthetic samples.
        Cheap, gives the residual network a stable starting point. Uses
        odte.dml_pricer.train_dml_bs().
    (2) Fine-tune on Heston Monte Carlo paths generated by
        odte.synth_options.Heston.simulate_paths. Loss target for prices
        is the PATH-AVERAGED payoff (Monte Carlo call value), so the
        residual network learns the Heston correction to BS.

Checkpoints at every stage; resumable.
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import time
from dataclasses import asdict
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import torch.nn.functional as F

from models.config import DMLConfig
from odte.dml_pricer import DMLPricer, bs_price_call, bs_greeks_call, train_dml_bs
from odte.synth_options import Heston, HestonParams

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Heston reference call price via Monte Carlo
# ---------------------------------------------------------------------------

def heston_mc_call_price(
    S: np.ndarray, K: np.ndarray, tau_years: np.ndarray, sigma: np.ndarray,
    r: np.ndarray, params: HestonParams, n_paths: int = 4000,
    n_steps: int = 64, seed: int = 0,
) -> np.ndarray:
    """Vectorized Heston MC call price for a batch of (S, K, τ, σ₀) rows.

    σ is used to seed instantaneous variance (σ²). Returns prices under risk-
    neutral measure with supplied r.
    """
    rng = np.random.default_rng(seed)
    B = len(S)
    prices = np.empty(B, dtype=np.float64)
    for i in range(B):
        p = HestonParams(mu=float(r[i]), kappa=params.kappa, theta=params.theta,
                         xi=params.xi, rho=params.rho, v0=float(sigma[i] ** 2))
        paths, _ = Heston(p).simulate_paths(
            S0=float(S[i]), T=float(tau_years[i]),
            steps=n_steps, n_paths=n_paths, seed=seed + i)
        payoff = np.maximum(paths[:, -1] - float(K[i]), 0.0)
        disc = math.exp(-float(r[i]) * float(tau_years[i]))
        prices[i] = disc * float(payoff.mean())
    return prices


# ---------------------------------------------------------------------------
# Stage (1): BS pretrain
# ---------------------------------------------------------------------------

def pretrain_bs(model: DMLPricer, steps: int = 2000, batch: int = 1024,
                device: str = "cpu", S_ref: float = 5500.0) -> dict:
    log.info("=== DML pretrain on Black-Scholes (%d steps) ===", steps)
    return train_dml_bs(model, steps=steps, batch=batch,
                        device=device, S_ref=S_ref)


# ---------------------------------------------------------------------------
# Stage (2): Heston fine-tune
# ---------------------------------------------------------------------------

def finetune_heston(model: DMLPricer, steps: int = 500, batch: int = 128,
                    device: str = "cpu", S_ref: float = 5500.0,
                    heston_params: Optional[HestonParams] = None,
                    n_mc_paths: int = 2000, n_mc_steps: int = 32,
                    lr: float = 1e-4,
                    tau_lo: float = 1 / (365 * 24), tau_hi: float = 3 / 365) -> dict:
    """Generate Heston MC targets on-the-fly; train the residual to match.

    Greek targets stay BS-based (no closed-form Greeks for Heston at the
    batch level on a laptop); the residual is shaped by price alone.

    tau_lo / tau_hi (in YEARS) bound the maturity sampling. Defaults are the
    0DTE band (1h .. 3d) used by the production pricer; widen them to validate
    that the residual learns Heston corrections at maturities where stochastic
    vol materially separates Heston from Black-Scholes.
    """
    log.info("=== DML fine-tune on Heston MC (%d steps, paths=%d) ===",
             steps, n_mc_paths)
    heston_params = heston_params or HestonParams()
    dev = torch.device(device)
    model = model.to(dev)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    history: list[dict] = []
    for step in range(steps):
        # Sample a small batch of option specs from the 0DTE-ish range.
        S = np.random.uniform(0.95 * S_ref, 1.05 * S_ref, size=batch)
        K = np.random.uniform(0.97 * S_ref, 1.03 * S_ref, size=batch)
        tau = np.random.uniform(tau_lo, tau_hi, size=batch)
        sigma = np.random.uniform(0.1, 0.6, size=batch)
        r = np.zeros(batch)

        target = heston_mc_call_price(
            S, K, tau, sigma, r, heston_params,
            n_paths=n_mc_paths, n_steps=n_mc_steps, seed=step)

        S_t = torch.tensor(S, dtype=torch.float32, device=dev)
        K_t = torch.tensor(K, dtype=torch.float32, device=dev)
        tau_t = torch.tensor(tau, dtype=torch.float32, device=dev)
        r_t = torch.tensor(r, dtype=torch.float32, device=dev)
        sig_t = torch.tensor(sigma, dtype=torch.float32, device=dev)
        y_t = torch.tensor(target, dtype=torch.float32, device=dev)

        p_hat, d_hat, g_hat, v_hat = model(S_t, K_t, tau_t, r_t, sig_t)
        # BS Greek targets (analytic) keep the gradient network well-behaved.
        d_bs, g_bs, v_bs = bs_greeks_call(S_t, K_t, tau_t, sig_t, r_t)

        loss_price = F.mse_loss(p_hat / K_t, y_t / K_t)
        loss_d = F.mse_loss(d_hat, d_bs)
        loss_g = F.mse_loss(g_hat * S_t, g_bs * S_t)
        loss_v = F.mse_loss(v_hat / S_t, v_bs / S_t)
        loss = loss_price + 0.2 * (loss_d + loss_g + loss_v)

        opt.zero_grad(); loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()

        history.append({"step": step, "total": float(loss.item()),
                        "price": float(loss_price.item())})
        if step % max(1, steps // 10) == 0:
            log.info("heston step %d  total=%.4f  price=%.4f",
                     step, loss.item(), loss_price.item())
    return {"history": history}


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def train(config: DMLConfig | None = None, device: str = "cpu",
          S_ref: float = 5500.0, bs_steps: int = 2000,
          heston_steps: int = 400, heston_batch: int = 64,
          n_mc_paths: int = 1000, n_mc_steps: int = 32,
          ckpt_dir: str | Path = "checkpoints") -> dict:
    cfg = config or DMLConfig()
    model = DMLPricer(cfg)
    pretrain_bs(model, steps=bs_steps, batch=cfg.batch_size,
                device=device, S_ref=S_ref)
    finetune_heston(model, steps=heston_steps, batch=heston_batch,
                    device=device, S_ref=S_ref,
                    n_mc_paths=n_mc_paths, n_mc_steps=n_mc_steps)
    ckpt_dir = Path(ckpt_dir); ckpt_dir.mkdir(parents=True, exist_ok=True)
    out = ckpt_dir / f"dml_pricer_finetuned_{int(time.time())}.pt"
    torch.save({"state": model.state_dict(), "cfg": asdict(cfg)}, out)
    log.info("DML checkpoint → %s", out)
    return {"ckpt": str(out)}


def _cli():
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--s-ref", type=float, default=5500.0)
    ap.add_argument("--bs-steps", type=int, default=2000)
    ap.add_argument("--heston-steps", type=int, default=400)
    ap.add_argument("--heston-batch", type=int, default=64)
    ap.add_argument("--n-mc-paths", type=int, default=1000)
    ap.add_argument("--n-mc-steps", type=int, default=32)
    ap.add_argument("--ckpt-dir", default="checkpoints")
    a = ap.parse_args()
    out = train(device=a.device, S_ref=a.s_ref, bs_steps=a.bs_steps,
                heston_steps=a.heston_steps, heston_batch=a.heston_batch,
                n_mc_paths=a.n_mc_paths, n_mc_steps=a.n_mc_steps,
                ckpt_dir=a.ckpt_dir)
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    _cli()
